// @generated by tools/generate-bridge.mjs; do not edit.

pub const GENERATED_BRIDGE_METHODS: &[&str] = &[
    "bridge.hello",
    "bridge.status",
    "diagnostics.snapshot",
    "discovery.start",
    "discovery.stop",
    "receiver.list",
    "receiver.connect",
    "receiver.disconnect",
    "receiver.trust",
    "receiver.forget",
    "session.load",
    "session.control",
    "session.selectTrack",
    "session.close",
    "companion.register",
    "companion.unregister",
    "credentialLease.create",
    "credentialLease.revoke",
    "mirror.negotiate",
];
