// @generated by tools/generate-bridge.mjs; do not edit.

export const BRIDGE_PROTOCOL_VERSION = 1 as const;
export const BRIDGE_METHODS = ["bridge.hello","bridge.status","diagnostics.snapshot","discovery.start","discovery.stop","receiver.list","receiver.connect","receiver.disconnect","receiver.trust","receiver.forget","session.load","session.control","session.selectTrack","session.close","companion.register","companion.unregister","credentialLease.create","credentialLease.revoke","mirror.negotiate"] as const;
export type BridgeMethod = (typeof BRIDGE_METHODS)[number];

export interface JsonObject { [key: string]: JsonValue; }
export interface JsonArray extends Array<JsonValue> {}
export type JsonValue = null | boolean | number | string | JsonArray | JsonObject;

export interface BridgeRequest { v: 1; id: string; method: BridgeMethod; params: JsonObject; }
export interface BridgeResponse<T extends JsonValue = JsonValue> {
  v: 1; id: string; ok: boolean; result?: T; error?: { code: string; message: string; recoverable: boolean; suggestedNextMode?: string; details?: JsonObject };
}
export interface BridgeEvent<T extends JsonValue = JsonValue> { v: 1; event: string; data: T; }
