import { readFile, mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = resolve(root, "schemas/bridge-v1.schema.json");
const schema = JSON.parse(await readFile(schemaPath, "utf8"));
const methods = schema.properties.method.enum;

const ts = `// @generated by tools/generate-bridge.mjs; do not edit.\n\n` +
  `export const BRIDGE_PROTOCOL_VERSION = 1 as const;\n` +
  `export const BRIDGE_METHODS = ${JSON.stringify(methods)} as const;\n` +
  `export type BridgeMethod = (typeof BRIDGE_METHODS)[number];\n\n` +
  `export interface JsonObject { [key: string]: JsonValue; }\n` +
  `export interface JsonArray extends Array<JsonValue> {}\n` +
  `export type JsonValue = null | boolean | number | string | JsonArray | JsonObject;\n\n` +
  `export interface BridgeRequest { v: 1; id: string; method: BridgeMethod; params: JsonObject; }\n` +
  `export interface BridgeResponse<T extends JsonValue = JsonValue> {\n` +
  `  v: 1; id: string; ok: boolean; result?: T; error?: { code: string; message: string; recoverable: boolean; suggestedNextMode?: string; details?: JsonObject };\n` +
  `}\n` +
  `export interface BridgeEvent<T extends JsonValue = JsonValue> { v: 1; event: string; data: T; }\n`;

const rustMethods = methods.map((method) => `    ${JSON.stringify(method)},`).join("\n");
const rust = `// @generated by tools/generate-bridge.mjs; do not edit.\n\n` +
  `pub const GENERATED_BRIDGE_METHODS: &[&str] = &[\n${rustMethods}\n];\n`;

await mkdir(resolve(root, "packages/bridge-types/src"), { recursive: true });
await mkdir(resolve(root, "crates/bridge/src"), { recursive: true });
await writeFile(resolve(root, "packages/bridge-types/src/generated.ts"), ts);
await writeFile(resolve(root, "crates/bridge/src/generated.rs"), rust);
